# -------------------- 基础 --------------------
use_gui: True          # 训练阶段通常不开 GUI

# 场景 -------------------------------------------------
scene:
  type: voxelized           # World 会自动选择 NavRLScene
  voxel:
    size: 1.0
  map:
    building_path: "assets/building/building.obj" # 建筑物模型路径
  obstacle:
    # ---- 静态障碍 ----
    num_obstacles: 2
    min_radius: 5
    max_radius: 10
    min_height: 60
    max_height: 200
    # ---- 动态障碍 ----
    dynamic:
      num_obstacles: 10    # 只要 >0 就会启用 DynamicVoxelizedScene
      min_radius: 5
      max_radius: 10
      min_height: 60
      max_height: 200
      max_speed: 2.0      # m/s
  region:
    x_min: -250   # 50m×50m 区域 / 500m×500m 区域
    x_max:  250
    y_min: -250
    y_max:  250
    z_min: 0
    z_max: 200

# 无人机 ------------------------------------------------
drone:
  init_pos: random
  urdf_path: "assets/cf2x.urdf"

# 动作 --------------------------------------------------
action:
  v_limit: 2.0          # m/s，连续速度上限

# 观测 --------------------------------------------------
observation:
  # 动态障碍
  num_dyn: 5
  dyn_feat_dim: 10      # [dir(3), dist, vel(3), size(3)] = 10
  # 静态射线
  num_h: 36             # 每 10°
  num_v: 3              # 水平 + 两个俯仰
  max_ray: 20.0         # m
  # 观测维度由 env 自动推算；如需归一化请在算法侧处理

# 奖励 --------------------------------------------------
reward:
  weights:
    vel:     1.0
    ss:      1.0
    ds:      1.0
    smooth:  0.1
    height:  0.1
  success_reward:    5.0
  collision_penalty: -5.0

# Episode ----------------------------------------------
episode:
  max_episode_timesteps: 400
  action_repeat: 60     # 与 navigation_env 保持一致